// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package infrastructure

import (
	"github.com/mazrean/gopendb-generator/cmd/interfaces/handler"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func InjectRootCmd() (*cobra.Command, error) {
	generate := handler.NewGenerate()
	command := newRootCmd(generate)
	return command, nil
}
