name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build -o genorm ./cmd/genorm/
      - uses: actions/upload-artifact@v3
        with:
          name: genorm
          path: ./genorm
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # go generate用に、golangci-lintの前にGoのinstallをする
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.3
        with:
          go_version_file: go.mod
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - run: go test ./... -v -coverprofile=./coverage.txt -race -vet=off
      - name: Upload coverage data
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.txt
      - uses: actions/upload-artifact@v3
        with:
          name: coverage.txt
          path: coverage.txt
