name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  GO_VERSION: '1.18'

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/setup-go@v2.2.0
      #  with:
      #    go-version: ${{ env.GO_VERSION }}
      - name: Setup Go
        run: |
          wget https://go.dev/dl/go1.18rc1.linux-amd64.tar.gz
          rm -rf $HOME/go
          tar -C $HOME/ -xzf go1.18rc1.linux-amd64.tar.gz
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Print Go Version
        run: go version
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - run: go mod download
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      #- uses: actions/setup-go@v2.2.0
      #  with:
      #    go-version: ${{ env.GO_VERSION }}
      - name: Setup Go
        run: |
          wget https://go.dev/dl/go1.18rc1.linux-amd64.tar.gz
          rm -rf $HOME/go
          tar -C $HOME/ -xzf go1.18rc1.linux-amd64.tar.gz
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2.1.7
        with:
          path: /tmp/go/cache
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-
      - run: go build -o genorm ./cmd/genorm/
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [mod]
    steps:
      #- uses: actions/setup-go@v2.2.0
      #  with:
      #    go-version: ${{ env.GO_VERSION }}
      - name: Setup Go
        run: |
          wget https://go.dev/dl/go1.18rc1.linux-amd64.tar.gz
          rm -rf $HOME/go
          tar -C $HOME/ -xzf go1.18rc1.linux-amd64.tar.gz
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Print Go Version
        run: go version
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - run: go generate ./...
      - run: go test ./... -v -coverprofile=./coverage.txt -race -vet=off
      - name: Upload coverage data
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt
          yml: ./codecov.yml
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage.txt
          path: coverage.txt
