name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build -o genorm ./cmd/genorm/
      - uses: actions/upload-artifact@v3
        with:
          name: genorm
          path: ./genorm
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - run: go test ./... -v -coverprofile=./coverage.txt -race -vet=off
      - name: Upload coverage data
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.txt
      - uses: actions/upload-artifact@v3
        with:
          name: coverage.txt
          path: coverage.txt
